import type { ITheme } from "@xterm/xterm";

// カラーテーマのプリセット定義。ui は styles.css の :root 変数（-- なし）に、
// xterm は各ペインの Terminal.options.theme にそのまま入る。
// ui の全キーは全プリセット必須（欠けると前のテーマの色が残る）。

export type ThemeId = "dark" | "light" | "solarized-dark" | "dracula" | "nord";

export type ThemePreset = {
  id: ThemeId;
  /** テーマ名は固有名詞なので翻訳しない */
  label: string;
  ui: Record<string, string>;
  xterm: ITheme;
};

export const DEFAULT_THEME: ThemeId = "dark";

const UI_KEYS = [
  "bg",
  "chrome",
  "line",
  "text",
  "dim",
  "accent",
  "alarm",
  "hover",
  "active-bg",
  "pane-bg",
  "focus-border",
  "pulse",
  "on-accent",
  "shadow",
  "diff-add-bg",
  "diff-add-fg",
  "diff-del-bg",
  "diff-del-fg",
  "ws-color-red",
  "ws-color-orange",
  "ws-color-yellow",
  "ws-color-green",
  "ws-color-blue",
  "ws-color-purple",
] as const;

export const THEMES: ThemePreset[] = [
  {
    id: "dark",
    label: "Dark",
    ui: {
      bg: "#07090b",
      chrome: "#11151a",
      line: "#1e252d",
      text: "#d6dbe0",
      dim: "#6b7885",
      accent: "#6ee7d0",
      alarm: "#f0a04b",
      hover: "#171c22",
      "active-bg": "#1a2027",
      "pane-bg": "#0d1013",
      "focus-border": "#2f3b46",
      pulse: "#7a5528",
      "on-accent": "#07090b",
      shadow: "rgba(0, 0, 0, 0.5)",
      "diff-add-bg": "#12351f",
      "diff-add-fg": "#7ee787",
      "diff-del-bg": "#47201f",
      "diff-del-fg": "#ff8f88",
      "ws-color-red": "#e06c75",
      "ws-color-orange": "#e5a55b",
      "ws-color-yellow": "#d9c07c",
      "ws-color-green": "#8cc265",
      "ws-color-blue": "#61afef",
      "ws-color-purple": "#c678dd",
    },
    xterm: {
      background: "#0d1013",
      foreground: "#d6dbe0",
      cursor: "#6ee7d0",
      selectionBackground: "#2a3540",
      black: "#0d1013",
      red: "#e06c75",
      green: "#8cc265",
      yellow: "#d9c07c",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#d6dbe0",
    },
  },
  {
    id: "light",
    label: "Light",
    ui: {
      bg: "#f4f5f6",
      chrome: "#e9ebee",
      line: "#d0d5da",
      text: "#24292f",
      dim: "#6e7a86",
      accent: "#0d8577",
      alarm: "#b45309",
      hover: "#dde1e6",
      "active-bg": "#d2d8de",
      "pane-bg": "#ffffff",
      "focus-border": "#8fa0ae",
      pulse: "#e0b880",
      "on-accent": "#ffffff",
      shadow: "rgba(0, 0, 0, 0.2)",
      "diff-add-bg": "#e6ffec",
      "diff-add-fg": "#1a7f37",
      "diff-del-bg": "#ffebe9",
      "diff-del-fg": "#cf222e",
      "ws-color-red": "#cf222e",
      "ws-color-orange": "#bc6b00",
      "ws-color-yellow": "#9a7b00",
      "ws-color-green": "#1a7f37",
      "ws-color-blue": "#0969da",
      "ws-color-purple": "#8250df",
    },
    xterm: {
      background: "#ffffff",
      foreground: "#24292f",
      cursor: "#0d8577",
      selectionBackground: "#c8d1da",
      black: "#24292f",
      red: "#c0392b",
      green: "#3f8b26",
      yellow: "#b58900",
      blue: "#0969da",
      magenta: "#8250df",
      cyan: "#1b7c83",
      white: "#6e7a86",
    },
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    ui: {
      bg: "#00212b",
      chrome: "#073642",
      line: "#0e4a5a",
      text: "#93a1a1",
      dim: "#586e75",
      accent: "#2aa198",
      alarm: "#cb4b16",
      hover: "#0a3540",
      "active-bg": "#0e4250",
      "pane-bg": "#002b36",
      "focus-border": "#268bd2",
      pulse: "#6a3a12",
      "on-accent": "#002b36",
      shadow: "rgba(0, 0, 0, 0.5)",
      "diff-add-bg": "#0a3d2e",
      "diff-add-fg": "#859900",
      "diff-del-bg": "#3d1a14",
      "diff-del-fg": "#dc322f",
      "ws-color-red": "#dc322f",
      "ws-color-orange": "#cb4b16",
      "ws-color-yellow": "#b58900",
      "ws-color-green": "#859900",
      "ws-color-blue": "#268bd2",
      "ws-color-purple": "#d33682",
    },
    xterm: {
      background: "#002b36",
      foreground: "#93a1a1",
      cursor: "#2aa198",
      selectionBackground: "#073642",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    ui: {
      bg: "#21222c",
      chrome: "#282a36",
      line: "#44475a",
      text: "#f8f8f2",
      dim: "#6272a4",
      accent: "#bd93f9",
      alarm: "#ffb86c",
      hover: "#343746",
      "active-bg": "#3c3f51",
      "pane-bg": "#282a36",
      "focus-border": "#bd93f9",
      pulse: "#8a5a30",
      "on-accent": "#21222c",
      shadow: "rgba(0, 0, 0, 0.5)",
      "diff-add-bg": "#1d3a2a",
      "diff-add-fg": "#50fa7b",
      "diff-del-bg": "#3c2130",
      "diff-del-fg": "#ff5555",
      "ws-color-red": "#ff5555",
      "ws-color-orange": "#ffb86c",
      "ws-color-yellow": "#f1fa8c",
      "ws-color-green": "#50fa7b",
      "ws-color-blue": "#8be9fd",
      "ws-color-purple": "#bd93f9",
    },
    xterm: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
    },
  },
  {
    id: "nord",
    label: "Nord",
    ui: {
      bg: "#242933",
      chrome: "#2e3440",
      line: "#3b4252",
      text: "#d8dee9",
      dim: "#7b88a1",
      accent: "#88c0d0",
      alarm: "#d08770",
      hover: "#333a47",
      "active-bg": "#3b4252",
      "pane-bg": "#2e3440",
      "focus-border": "#81a1c1",
      pulse: "#6d4a3a",
      "on-accent": "#2e3440",
      shadow: "rgba(0, 0, 0, 0.5)",
      "diff-add-bg": "#2e4238",
      "diff-add-fg": "#a3be8c",
      "diff-del-bg": "#452c31",
      "diff-del-fg": "#bf616a",
      "ws-color-red": "#bf616a",
      "ws-color-orange": "#d08770",
      "ws-color-yellow": "#ebcb8b",
      "ws-color-green": "#a3be8c",
      "ws-color-blue": "#81a1c1",
      "ws-color-purple": "#b48ead",
    },
    xterm: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      selectionBackground: "#434c5e",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
    },
  },
];

export function themeById(id: string | undefined): ThemePreset {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

export function xtermThemeFor(id: ThemeId): ITheme {
  return themeById(id).xterm;
}

/** :root の CSS 変数を書き換えて UI 全体を再着色する */
export function applyThemeCss(id: ThemeId): ThemePreset {
  const preset = themeById(id);
  const style = document.documentElement.style;
  for (const key of UI_KEYS) style.setProperty(`--${key}`, preset.ui[key]);
  return preset;
}
